import { api } from './client'
export const getProjects          = () => api.get('/api/projects').then(r => r.data)
export const getProject           = (id: string) => api.get(`/api/projects/${id}`).then(r => r.data)
export const createProject        = (data: any) => api.post('/api/projects', data).then(r => r.data)
export const createPhase          = (pid: string, data: any) => api.post(`/api/projects/${pid}/phases`, data).then(r => r.data)
export const getTasks             = (pid: string) => api.get(`/api/projects/${pid}/tasks`).then(r => r.data)
export const createTask           = (pid: string, data: any) => api.post(`/api/projects/${pid}/tasks`, data).then(r => r.data)
export const updateTask           = (pid: string, tid: string, data: any) => api.put(`/api/projects/${pid}/tasks/${tid}`, data).then(r => r.data)
export const getReviews           = (pid: string) => api.get(`/api/projects/${pid}/reviews`).then(r => r.data)
export const createReview         = (pid: string, data: any) => api.post(`/api/projects/${pid}/reviews`, data).then(r => r.data)
export const getWeeklyReports     = (pid: string) => api.get(`/api/projects/${pid}/weekly-reports`).then(r => r.data)
export const generateWeeklyReport = (pid: string) => api.post(`/api/projects/${pid}/weekly-reports`).then(r => r.data)
export const getPreReviewBrief    = (pid: string) => api.get(`/api/projects/${pid}/nudges/pre-review-brief`).then(r => r.data)
export const sendNudge            = (pid: string, taskId: string) => api.post(`/api/projects/${pid}/nudges/${taskId}`).then(r => r.data)
export const closeProject         = (pid: string, data: any) => api.post(`/api/projects/${pid}/close`, data).then(r => r.data)

export const getTaskUpdates  = (pid: string, tid: string) => api.get(`/api/projects/${pid}/tasks/${tid}/updates`).then(r => r.data)
export const createTaskUpdate = (pid: string, tid: string, data: any) => api.post(`/api/projects/${pid}/tasks/${tid}/updates`, data).then(r => r.data)

export const getReviewAgenda   = (pid: string) => api.get(`/api/projects/${pid}/nudges/review-agenda`).then(r => r.data)
export const createReviewFull  = (pid: string, data: any) => api.post(`/api/projects/${pid}/reviews`, data).then(r => r.data)

export const getReviewSummary = (pid: string) => api.get(`/api/projects/${pid}/nudges/review-summary`).then(r => r.data)
export const getCCRs   = (pid: string) => api.get(`/api/projects/${pid}/ccr`).then(r => r.data)
export const createCCR = (pid: string, data: any) => api.post(`/api/projects/${pid}/ccr`, data).then(r => r.data)
